#include "assmerge.h"
#include <qfile.h>
#include <qdebug.h>
#include <qtextcodec.h>

int assmerge::getcnlines(QString file, int option)
{
    int lines=0;
    QFile *fp = new QFile(file);
    fp->open(QIODevice::ReadOnly|QIODevice::Text);
    QTextStream in(fp);
    in.setCodec(QTextCodec::codecForName("Unicode") );
    fp->seek(0);
    while(!in.atEnd())
    {
        switch (option)
        {
            case 0:     //中文翻译
            {
                QString temp = in.readLine(); //读一行是一行
                qDebug()<< temp;
                if(temp.contains(QRegExp("[\\x4e00-\\x9fa5]+")))lines++;
                break;
            }
            case 3:     //获取srt行数
            {
                QString seq = in.readLine(); //序号
                QString timeline = in.readLine(); //时间区间
                QString script = in.readLine(); //台词（因为修正过，所以必只有一行）
                if(script.length()) in.readLine();//空行
                if(seq == NULL || timeline == NULL) return lines;//不完整的行不计入字幕
                lines++;
                break;
            }
            default:
            {
                QString temp = in.readLine();
                in.readLine();
                if(temp == NULL) return lines;
                lines++;
                break;
            }
        }
    }
    fp->close();
    return lines;
}

int assmerge::outputass(QString infile1,QString infile2, QString outfile,QString cncode, QString encode)
{
    QFile *fpin1 = new QFile(infile1);
    QFile *fpin2 = new QFile(infile2);
    QFile *fpout = new QFile(outfile);
    fpin1->open(QIODevice::ReadOnly|QIODevice::Text);
    fpin2->open(QIODevice::ReadOnly|QIODevice::Text);
    fpout->open(QIODevice::WriteOnly|QIODevice::Text);
    QTextStream txtin1(fpin1);
    fpin1->seek(0);
    QTextStream txtin2(fpin2);
    fpin2->seek(0);
    QTextStream txtout(fpout);
    txtout.setCodec(QTextCodec::codecForName("Utf-8"));
    txtin2.setCodec(QTextCodec::codecForName("Utf-8"));
    //ass字幕文件头
    txtout << "[Script Info]"<< endl;
    txtout << "; This ass is generated by Billy Goodman's subtitle tool, version 1.1, codename: novice_847"   << endl;
    txtout << "; https://zhwikizmz.cn"   << endl;
    txtout << "Title: BG auto generated file"   << endl;
    txtout << "ScriptType: v4.00+"   << endl;
    txtout << "PlayResX: 1920"   << endl;
    txtout << "PlayResY: 1080"   << endl;
    txtout << "ScaledBorderAndShadow: yes"   << endl << endl;
    txtout << "[BG Padding Information]"   << endl;
    txtout << "Hello, motherfucker~"   << endl;
    txtout << "I'll evolve into a powerful, versatile tool one day~"   << endl << endl;
    txtout << "[V4+ Styles]"   << endl;
    txtout << "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"   << endl;
    txtout << "Style: Default,Arial,13,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1.33333,1.33333,2,7,7,7,1"   << endl << endl;
    txtout << "[Events]" << endl;
    txtout << "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text" << endl;
    QString Start,End,line,script;
    while(!txtin1.atEnd())
    {
        txtout << "Dialogue: 0,"; //ass必备
        txtin1.readLine();//跳过序列号
        line=txtin1.readLine();//读取时间轴
        Start=line.mid(1,10); //截取起始时间
        End = line.mid(18,10); //截取终止时间
        Start.replace(",",".");//srt时间转ass时间格式
        End.replace(",",".");//同上
        txtout << Start << "," << End << ",";
        txtout << "Default,,0,0,0,,";//样式，默认就行
        line = txtin2.readLine();//台词行
        while(!line.contains(QRegExp("[\\x4e00-\\x9fa5]+")) && !txtin2.atEnd())line = txtin2.readLine();//直到读取到下一行中文
        script = txtin1.readLine();
        if(script.length())
                txtout << cncode << line << "\\N" << encode << script << endl;
        else
                txtout << cncode << line << endl;
        txtin1.readLine();//跳过空行
    }
    fpin1->close();
    fpin2->close();
    fpout->close();
    return 0;
}
